canvas=document.getElementById("meinCanvas");
color="blue";
color2="black";
color3="red";
color4="yellow";
color5="green";
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle= color;
ctx.lineWidth = 5;
ctx.arc(200 , 200 , 40 ,0,2*Math.PI );
ctx.stroke();
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle= color2;
ctx.lineWidth = 5;
ctx.arc(270 , 200 , 40 ,0,2*Math.PI );
ctx.stroke();
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle= color3;
ctx.lineWidth = 5;
ctx.arc(340 , 200 , 40 ,0,2*Math.PI );
ctx.stroke();
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle= color4;
ctx.lineWidth = 5;
ctx.arc(240 , 260 , 40 ,0,2*Math.PI );
ctx.stroke();
ctx=canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle= color5;
ctx.lineWidth = 5;
ctx.arc(310 , 260 , 40 ,0,2*Math.PI );
ctx.stroke();